<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
<?php use Phalcon\Tag; ?>

<h2>Sign using this form</h2>

<?php echo Tag::form("signup/register"); ?>

<p>
    <label for="name">Имя</label>
    <?php echo Tag::textField("name") ?>
</p>

<p>
    <label for="name">E-Mail</label>
    <?php echo Tag::textField("email") ?>
</p>

<p>
    <?php echo Tag::submitButton("Регистрация") ?>
</p>

</form>
</body>
</html>
